import DataScheme from "./DataScheme.ts";
import DataStore from "./DataStore.ts";
import DatabaseInfo from "./DatabaseInfo.ts";
import DatabaseVersion from "./DatabaseVersion.ts";
import Device from "./Device.ts";
import FieldInfo from "./FieldInfo.ts";
import IndexInfo from "./IndexInfo.ts";
import RTableDef from "./RTableDef.ts";
import RequestDef from "./RequestDef.ts";
import RequestProcessor from "./RequestProcessor.ts";
import Response from "./Response.ts";
import ResponseResult from "./ResponseResult.ts";
import SelectColumnType from "./SelectColumnType.ts";
import TableDef from "./TableDef.ts";
import TableInfo from "./TableInfo.ts";
import Validator from "./Validator.ts";
import { default as ABDField, default as Field } from "./abd-fields/ABDField.ts";
import abdFields from "./abd-fields/index.ts";
import abdValidators from "./abd-validators/index.ts";
export { DataScheme, DataStore, RequestDef, Response, ResponseResult as ResponseResult };
declare class abData_Class {
    #private;
    get debug(): boolean;
    get fields(): typeof abdFields;
    get validators(): typeof abdValidators;
    get version(): number;
    get ABDField(): typeof ABDField;
    get Device(): typeof Device;
    get DataScheme(): typeof DataScheme;
    get DataStore(): typeof DataStore;
    get DatabaseInfo(): typeof DatabaseInfo;
    get DatabaseVersion(): typeof DatabaseVersion;
    get Field(): typeof Field;
    get FieldInfo(): typeof FieldInfo;
    get IndexInfo(): typeof IndexInfo;
    get Response(): typeof Response;
    get Result(): typeof ResponseResult;
    get RequestDef(): typeof RequestDef;
    get RequestProcessor(): typeof RequestProcessor;
    get RTableDef(): typeof RTableDef;
    get SelectColumnType(): typeof SelectColumnType;
    get TableDef(): typeof TableDef;
    get TableInfo(): typeof TableInfo;
    get Validator(): typeof Validator;
    constructor();
    error(errorTitle: string, error: Error): void;
    setDebug(debug: boolean): void;
}
declare const abData: abData_Class;
export default abData;
