import ABDAutoIncrementId from "./ABDAutoIncrementId.ts";
import ABDBlob, { type ABDBlob_Type } from "./ABDBlob.ts";
import ABDBool from "./ABDBool.ts";
import ABDDate from "./ABDDate.ts";
import ABDDateTime from "./ABDDateTime.ts";
import ABDFloat from "./ABDFloat.ts";
import ABDId from "./ABDId.ts";
import ABDInt from "./ABDInt.ts";
import ABDJSON, { type ABDJSON_Type } from "./ABDJSON.ts";
import ABDLong from "./ABDLong.ts";
import ABDString from "./ABDString.ts";
import ABDText, { type ABDText_Type } from "./ABDText.ts";
import ABDTime from "./ABDTime.ts";
import type { ABDField_Properties } from "./ABDField.ts";
declare class abdField_Class {
    get ABDAutoIncrementId(): typeof ABDAutoIncrementId;
    get ABDBlob(): typeof ABDBlob;
    get ABDBool(): typeof ABDBool;
    get ABDDate(): typeof ABDDate;
    get ABDDateTime(): typeof ABDDateTime;
    get ABDFloat(): typeof ABDFloat;
    get ABDId(): typeof ABDId;
    get ABDInt(): typeof ABDInt;
    get ABDJSON(): typeof ABDJSON;
    get ABDLong(): typeof ABDLong;
    get ABDString(): typeof ABDString;
    get ABDTime(): typeof ABDTime;
    get ABDText(): typeof ABDText;
    AutoIncrementId(): ABDAutoIncrementId;
    Blob(type: ABDBlob_Type, properties?: ABDField_Properties): ABDBlob;
    Bool(properties?: ABDField_Properties): ABDBool;
    Date(properties?: ABDField_Properties): ABDDate;
    DateTime(properties?: ABDField_Properties): ABDDateTime;
    Float(properties?: ABDField_Properties): ABDFloat;
    Id(): ABDId;
    Int(properties?: ABDField_Properties): ABDInt;
    JSON(type: ABDJSON_Type, properties?: ABDField_Properties): ABDJSON;
    Long(properties?: ABDField_Properties): ABDLong;
    String(size: number, properties?: ABDField_Properties): ABDString;
    Time(properties?: {}): ABDTime;
    Text(type: ABDText_Type, properties?: {}): ABDText;
}
declare const abdFields: abdField_Class;
export default abdFields;
